#Use %player% to display name
#Use ยง to color

joinmessage: "%player% ยง5Joined the game"
quitmessage: "%player% ยง5Left the server"

titlemessage: "Welcome ยง5%player%"
subtitlemessage: "To the server!"